### ISSUE TITLE
New 100Mpc galaxy catalogue to add (LASr)

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#102]
New catalogue released which is focused on a complete sample of nearby AGN, and it also claims to 

Local AGN Survey (LASr)  .... presumably pronounced "las - r" 

[https://arxiv.org/abs/2003.05959)]

49,000 galaxies of which 4300 are "known" AGN. 

Need to quantify this sample and add to Sherlock for cross-matching. They seem to have done a job on cleaning - see their Figure 7, which could be very useful for us.

**Comment by thespacedoctor** [comment]
Read the paper and understand the content of the catalogue now, but can't find the catalogue to download from anywhere. Paper states that the full LASr-GPS table is available online in digital format ... but no link.

Emailing the lead author.

**Comment by thespacedoctor** [comment]
Found it!

[![](https://live.staticflickr.com/65535/50247846233_18393c1751_z.png)](https://live.staticflickr.com/65535/50247846233_18393c1751_o.png)

**Comment by thespacedoctor** [comment]
LAS-r has now replaced Glade in all PanSTARRS databases (also altered all sherlock_crossmatches tables to host new W1 and W1Err columns). All algorithms have been updated.

Just Lasair to go now.

**Comment by thespacedoctor** [comment]
Database tables ported to Lasair and Lasiar-dev environments. Algorithms updated. Sherlock tested and working.
