### ISSUE TITLE
Bug in the Sherlock Redshift-to-Distance Calc

### ISSUE THREAD

**Issue by mFulton07** [thespacedoctor/sherlock#103]
There seems to be an issue within Sherlock's redshift-to-direct-distance calculation that is quoted in the context description of ATLAS objects.

Examples:

The probable host galaxy of ATLAS20jkz: https://star.pst.qub.ac.uk/sne/atlas4/candidate/1125806230454903000/ has a redshift of z = 0.007 from NED. Sherlock calculates this to be 16 Mpc; however, NED quotes the distance to be around 23 Mpc - which is more accurate.

Also, the probable host galaxy of ATLAS20jjt: https://star.pst.qub.ac.uk/sne/atlas4/candidate/1123633131111356900/ has a slightly larger redshift of z = 0.008 from NED. Sherlock calculates this to be 19.7 Mpc; however, it should be higher than 23 Mpc if following from the above example. Note in this case NED quotes the distance to be around 14 Mpc for this redshift - which is much worse than Sherlock's performance.

**Comment by thespacedoctor** [comment]
What's not clear from the terse Sherlock annotation is that the reported distance to the transient host can be either from a 'direct' distance measurement via some flavour of standard candle (e.g. Cepheids) or from a conversion from redshift to distance. The direct distance measurement is obviously to be considered more reliable especially within the nearby universe where [local flow](http://astronomy.swin.edu.au/cosmos/L/Local+Flow) causes considerable deviation from the Hubble flow (i.e. the measured redshift of galaxies cannot be solely attributed to Hubble flow and the redshift-to-distance conversions can be considerably inaccurate). 

For ATLAS20jkz where there is a direct distance reported in the Glade catalogue of 16.04 Mpc .. but where this distance comes from is anyone's guess.

ATLAS20jjt has a secure direct distance measurement in the [NED-D catalogue](https://ned.ipac.caltech.edu/Library/Distances/) of 19.7 Mpc.

**Comment by mFulton07** [comment]
Okay, this is handy to know. I was under the assumption these were Sherlock's own distance calculations using the quoted redshift. Thanks for the explanation!
