### ISSUE TITLE
real transient in galaxy mis-classified as VS

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/sherlock#110]
Need to investigate:

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1142408831121531600/

**Comment by thespacedoctor** [comment]
![](https://live.staticflickr.com/65535/49973396658_d6717a508e_o.png)

Note the matched 'star' seems to be another node in an external galaxy masquerading as a star in SDSS DR12. The object has persisted as a star through to DR15 (click on the link in the ATLAS pages to view). 

If I remove the 'synonym' classification for SDSS stars the classifier is allowed to continue and grabs all of the 'associations' for this object. We now get the correct classification of SN. See below for annotation and complete result set.

> The transient is possibly associated with <em><a href="https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=SDSSJ142407.97+121543.9&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES">SDSSJ142407.97+121543.9</a></em>; a B=20.37 mag galaxy found in the NED/SDSS/GLADE catalogues. It's located 12.72" S, 13.79" W (0.3 Kpc) from the galaxy centre. A host z=0.027 implies a <em>m - M =</em> 35.34.

```text
Transient's Predicted Classification: SN
Suggested Associations:
+-------------------+-------+------------+---------------------------------+---------------------------+------------------------+---------------------------+-------------+-------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
| association type  | rank  | rankScore  | catalogue table name            | catalogue object id       | catalogue object type  | catalogue object subtype  | raDeg       | decDeg      | separationArcsec  | physical separation kpc  | direct distance  | distance  | z     | photoZ  | photoZErr  | Mag    | MagFilter  | MagErr  | classification reliability  | merged rank  |
+-------------------+-------+------------+---------------------------------+---------------------------+------------------------+---------------------------+-------------+-------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
| SN                | 1     | 1952.01    | NED/SDSS/GLADE                  | SDSSJ142407.97+121543.9   | galaxy                 | multiple                  | 216.037035  | 12.2585632  | 0.50              | 0.27                     |                  | 116.73    | 0.03  |         |            | 19.80  | r          | 0.11    | association                 |              |
| SN                |       | 1952.01    | SDSS DR12 SpecObjAll Table      | 1237662528993231076       | galaxy                 | 3                         | 216.033206  | 12.2622043  | 18.76             | 10.07                    |                  | 116.67    | 0.03  |         |            | 19.80  | r          | 0.11    | association                 | 1            |
| SN                |       | 1952.01    | NED                             | SDSS J142407.97+121543.9  | galaxy                 | G                         | 216.03325   | 12.26222    | 18.69             | 10.03                    |                  | 116.73    | 0.03  |         |            | 17.90  | unk        |         | association                 | 1            |
| SN                |       | 1952.01    | The GLADE Catalogue v2.3        | SDSSJ142407.97+121543.9   | galaxy                 | G                         | 216.033     | 12.26217    | 19.22             | 11.26                    | 120.84           | 118.50    | 0.03  |         |            | 20.37  | B          | 0.50    | association                 | 1            |
| VS                |       | 1952.01    | SDSS DR12 PhotoObjAll Table     | 1237662528993231080       | star                   | 6                         | 216.037035  | 12.2585632  | 0.50              |                          |                  |           |       |         |            | 20.15  | r          | 0.45    | association                 | 1            |
| SN                | 2     | 1952.06    | NED/NED D/SDSS/PS1/GLADE/2MASS  | KUG1421+124               | galaxy                 | multiple                  | 216.037792  | 12.25853    | 2.40              | 1.16                     | 99.50            | 114.62    | 0.03  |         |            | 16.62  | r          | 0.00    | association                 |              |
| SN                |       | 1952.06    | SDSS DR12 SpecObjAll Table      | 1237662528993231075       | galaxy                 | 3                         | 216.038027  | 12.2586606  | 3.17              | 1.68                     |                  | 114.75    | 0.03  |         |            | 15.02  | r          | 0.03    | association                 | 2            |
| SN                |       | 1952.06    | SDSS DR12 PhotoObjAll Table     | 1237662528993231075       | galaxy                 | 3                         | 216.038027  | 12.2586606  | 3.17              | 2.14                     |                  | 149.04    |       | 0.03    | 0.01       | 15.02  | r          | 0.03    | association                 | 2            |
| SN                |       | 1952.06    | PanSTARRS DR1                   | 122712160379850826        | galaxy                 |                           | 216.038024  | 12.2586055  | 3.17              |                          |                  |           |       |         |            | 16.62  | r          | 0.00    | association                 | 2            |
| SN                |       | 1952.06    | The GLADE Catalogue v2.3        | 51437                     | galaxy                 | G                         | 216.03804   | 12.258517   | 3.27              |                          |                  |           |       |         |            | 15.36  | B          |         | association                 | 2            |
| SN                |       | 1952.06    | 2MASS XSC                       | 14240912+1215306          | galaxy                 |                           | 216.03804   | 12.258517   | 3.27              |                          |                  |           |       |         |            | 13.10  | J          | 0.04    | association                 | 2            |
| SN                |       | 1952.06    | NED                             | KUG 1421+124              | galaxy                 | G                         | 216.037792  | 12.25853    | 2.40              | 1.27                     |                  | 114.62    | 0.03  |         |            | 15.60  | unk        |         | association                 | 2            |
| SN                |       | 1952.06    | NED-D Galaxy Catalogue v13.1    | KUG 1421+124              | galaxy                 | G                         | 216.037792  | 12.25853    | 2.40              | 1.16                     | 99.50            |           |       |         |            | 15.60  | unk        |         | association                 | 2            |
+-------------------+-------+------------+---------------------------------+---------------------------+------------------------+---------------------------+-------------+-------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
```


The star however now gets merged with the wrong galaxy and throws us off from the best match for some reason (rank 2 should trump rank 1). Investigating further.

**Comment by smarttgit** [comment]
Different issue to the one above -  VS classification because of synonym, no ambiguity in identification of host object. 

SDSS gives clear galaxy though. The 2MASS/Gaia classification given higher rankScore ? 

Could understand Gaia being ranked higher than SDSS. Although not 2MASS.  The host is r = 16.5, probably for bright objects which are synonyms, we could rank SDSS above Gaia ? 
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1015500820044104000/

**Comment by smarttgit** [comment]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1012702510101555200/

This one a bit strange. classified as VS, but the text says "The transient is synonymous with 95680217600062099; an r=14.98 mag galaxy found in the PS1 catalogue. It's located 1.5" from the galaxy core."

So the sherlock object is a galaxy , but classed as VS 

And Sherlock should have latched onto this being NGC 567 with z = 0.023

NGC 0567
--




NGC 0567
--

**Comment by thespacedoctor** [comment]
Here is a source with a similar issue - synonymous with Millisquas AGN, SDSS star BUT really associated with NGC4470

**Comment by thespacedoctor** [comment]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1221607950365056800

**Comment by thespacedoctor** [comment]
I'm pleased to report that all transients reported in this issue are now getting associated correctly ...

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1142408831121531600/ - NOW CORRECT

> The transient is possibly associated with <em><a href="https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=KUG1421+124&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES">KUG1421+124</a></em>; a J=13.10 mag galaxy found in the NED_D/SDSS/2MASS/PS1 catalogues. It's located 0.62" N, 3.10" W (1.1 Kpc) from the galaxy centre. A host distance of 99.5 Mpc(z=0.026) implies a <em>m - M =</em> 34.99.


https://star.pst.qub.ac.uk/sne/atlas4/candidate/1015500820044104000/ - NOW CORRECT

> The transient is possibly associated with <em><a href="http://skyserver.sdss.org/dr12/en/tools/explore/Summary.aspx?id=1237679254132097083">SDSS J015500.84-044103.4</a></em>; a J=15.65 mag galaxy found in the SDSS/2MASS/PS1/GAIA catalogues. It's located 0.17" S, 0.60" W from the galaxy centre.


https://star.pst.qub.ac.uk/sne/atlas4/candidate/1012702510101555200/ - NOW CORRECT


> The transient is synonymous with <em><a href="https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=NGC0567&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES">NGC0567</a></em>; an r=14.98 mag galaxy found in the NED_D/SDSS/PS1 catalogues. It's located 0.9" (0.5 Kpc) from the galaxy core. A host distance of 107.0 Mpc(z=0.023) implies a <em>m - M =</em> 35.15.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1221607950365056800 - NOW CORRECT

> The transient is possibly associated with <em><a href="https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=IC5179&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES">IC5179</a></em>; a J=9.65 mag galaxy found in the NED/NED_D/2MASS/LASR catalogues. It's located 18.40" S, 13.95" W (4.7 Kpc) from the galaxy centre. A host distance of 41.6 Mpc(z=0.011) implies a <em>m - M =</em> 33.10.


https://star.pst.qub.ac.uk/sne/atlas4/candidate/1183751131372815500/ - NOW CORRECT


> The transient is possibly associated with <em><a href="https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=CGCG201-019&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES">CGCG201-019</a></em>; a J=11.96 mag galaxy found in the NED/2MASS/PS1/LASR catalogues. It's located 3.36" S, 9.53" E (4.8 Kpc) from the galaxy centre. A host distance of 97.3 Mpc(z=0.022) implies a <em>m - M =</em> 34.94.


https://star.pst.qub.ac.uk/sne/atlas4/candidate/1110259320161732600/ - NOW CORRECT

> The transient is possibly associated with <em><a href="https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=NGC3508&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES">NGC3508</a></em>; a J=10.81 mag AGN found in the NED/SDSS/2MASS/LASR/PS1 catalogues. It's located 9.86" S, 3.13" W (2.9 Kpc) from the AGN centre. A host distance of 57.9 Mpc(z=0.013) implies a <em>m - M =</em> 33.81.
