### ISSUE TITLE
Object should have been in Pan-STARRS fast track list

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#111]
This object is in the eyeball list along with other objects, but should definitely have been in the fast track list!

https://star.pst.qub.ac.uk/sne/ps13pi/psdb/candidate/1231856861001356100/

**Comment by thespacedoctor** [comment]
yes - a small ranking issue. Fixed now and pushed out in Sherlock v2.1.3 (alongside a change to checking MySQL triggers). [Changelog here](https://qub-sherlock.readthedocs.io/en/master/changes_link.html).

**Comment by thespacedoctor** [comment]
Hi @genghisken - reopening this issue as Sherlock was bumped to v2.1.3. I forgot we had agreed I should leave issues involving a version change open so you could close them whenever you propagated the upgrade through the various environments.

**Comment by genghisken** [comment]
No problem - are there any algorithm changes?  If not I'll bump the versions across the board.  We could do with a version number for the algorithms themselves.

**Comment by thespacedoctor** [comment]
No algorithm change.

> We could do with a version number for the algorithms themselves.

That's a nice idea. What do you think about the idea of having a default algorithm that most survey setups could/should use. This would run by default if Sherlock doesn't find a 'search algorithm' section in the external YAML file -  i.e. a user can override the default algorithm by including their customise version in the YAML file.

**Comment by genghisken** [comment]
Great - all sherlocks upgraded to v2.1.3 across the board (ATLAS, Pan-STARRS, Lasair, even defunct Lasair-dev)

Where would the 'default' algorithm live - in a separate YAML file?  I'm guessing you wouldn't want to hard wire it into the code anywhere.  Also - it occurs to me that we have common algorithms for all surveys at the moment.  We used to have divergent algorithms for PS and ATLAS because of the size of the ATLAS pixels.  (Different synonym values I think.)  We might want to revisit that in future.

**Comment by genghisken** [comment]
Also - for the algorithms - as well as a version we might want a hash so we know if the alternate algorithms have been tampered with (even if accidentally).

**Comment by thespacedoctor** [comment]
The default algorithm can live beside the code in another YAML file. It would be packaged and delivered with the code on a PyPI install. The settings in this file would get read first and then the user's own settings file. This means if the user has a 'search algorithm' block it simply overrides the default algorithm. Very simple.

With this method, the algorithm would be versioned WITH the code so no need for separate version numbers which can only end in pain.

> we might want a hash so we know if the alternate algorithms have been tampered with

Would this be recorded in the database??

**Comment by thespacedoctor** [comment]
closing this issue - will create another for versioned, default algorithm
