### ISSUE TITLE
A galaxy "group" being selected from NED rather than the galaxy 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#113]
The NGC 4321 "Group" is at a different position and redshif to the galaxy NGC4321 and hence the offsets and redshifts are not quite correct 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1122256151154934200/

Tricky one, as we do want to associate with galaxy clusters or groups. But in a different way, and the galaxy itself should always trump the group/cluster.

**Comment by thespacedoctor** [comment]
Yes - I only just discovered this issue while digging into the volume-limited data yesterday. I think the solution may be to push the galaxy groups/clusters/pair/triplet/lens into the 'NED other' category. This would mean these sources would only get matched if another association was not found (much like the NED IrS sources). What do you think?

**Comment by smarttgit** [comment]
Yes agree

**Comment by thespacedoctor** [comment]
I moved the following NED object types from the `tcs_view_galaxy_ned_stream` view to the `tcs_view_galaxy_like_ned_stream` view in the Sherlock database:

- GClstr
- GGroup
- GPair
- GTrpl
- G_Lens

They now join the ranks of 'UvS', 'UvES', 'IrS', 'VisS', 'HII' objects. Transients only get matched against these objects if no other synonym or association matches are found. QUB and ROE databases now reflect these changes.

No algorithm or code changes are required.
