### ISSUE TITLE
Investigate Glade catalogue's direct distances

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/sherlock#114]
For example, this [transient](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1094713520245208700/) has a direct distance quoted from Glade, but not in NED or NED-D

**Comment by thespacedoctor** [comment]
And this one: https://star.pst.qub.ac.uk/sne/atlas4/candidate/1224737731395250700/

**Comment by thespacedoctor** [comment]
From [Dalya et al. (2018)](https://arxiv.org/abs/1804.05709):

> 21: Luminosity distance measurement flag. 0: the object has neither measured distance nor measured redshift value. 1: the object has measured redshift value from which we have calculated its distance. 2: the object has measured distance value from which we have calculated its redshift. 3: we have replaced the measured photometric redshift with spectroscopic redshift from the 2MASS Redshift Survey catalogue, from which we have calculated its distance.

The first transient distance above is from group 2 so *should* be fine. The second is from group 3 so should not be reported as a direct distance. However, as Glade is from an amalgamation of 5 legacy galaxy catalogues and the providence of the distances reported is hard to ascertain I think we should move to disregard all distance measurements in Glade. We have NED and NED-D.

I might even go one step further and suggest we stop using Glade altogether. IMHO I think it just adds noise to the Sherlock classifications. Thoughts welcome.

**Comment by thespacedoctor** [comment]
@smarttgit and @genghisken , any objection to me removing Glade entirely from our search algorithms? Debugging the volume limited search results has proved to me how disruptive/distracting this catalogue has been. It's definitely having an overall negative impact on the classification results and there is little information in the catalogue not already covered by NED/NED-D.

**Comment by genghisken** [comment]
No objections from me!  I'm thoroughly fed up of seeing random GLADE z & distances that seem to have no externally verifiable origins.

**Comment by smarttgit** [comment]
Yes, happy with that. Also see Issue #102 - looks like very clean catalogue for d < 100 Mpc

**Comment by thespacedoctor** [comment]
LAS-r has now replaced Glade. 

RIP Glade.
