### ISSUE TITLE
Nuclear Transient misclassified as VS

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#116]
Not quite sure what happened here...  This nuclear transient got classified as VS (in both ATLAS and Lasair - so at least it's consistent!).  Gaia DR2 not quite so reliable when it comes to star/galaxy separation!

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1165812961020703100/
https://lasair.roe.ac.uk/object/ZTF20abisysx/

Turns out that this is apparently a TDE.  See:

https://wis-tns.weizmann.ac.il/astronotes/astronote/2020-143

**Comment by mFulton07** [comment]
Adding another example of the VS misclassification instead of creating an entirely new issue.

GOTO SN Ia reported to TNS. We saw it a week before GOTO but it got tagged as a VS in ATLAS. ATLAS object is very close to the core so this should have at least been flagged as an NT.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1010851411170309300/

It was the 2MASS/GAIA catalogues that gave it the star label. The host is a known galaxy in NED and also SDSS (DR15), however, it is recorded without a redshift in both.

**Comment by thespacedoctor** [comment]
**SHORT ANSWER:** We have a compounded issue where the transient coordinates read from the `tcs_latest_object_stats` database table lie right on top of the underlying catalogued source which is identified as stellar in most catalogues, and also I removed the synonymous NT matching classification for fainter galaxy sources in favour a SN association (see issue #99). Re-adding a PS1 general synonymous match as 'SN' instead of 'NT' has solved the issue.

**LONG ANSWER:** For the below I am using ATLAS object '[1000527920285242200](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1000527920285242200/)' as an example. Sherlock flagged this source as a VS, but ASSASN viewed it as a non-stellar transient and pushed it to the TNS (thanks to Michael for reporting). See screengrab below for context.

![](https://live.staticflickr.com/65535/50172827641_d59f56444f_o.png)

Currently when Sherlock runs on the ATLAS4 database it reads the RA and DEC coordinates from the `tcs_latest_object_stats`:

RA: 1.36599  
DEC: -28.8775885714286  

Here are the Sherlock results from those coordinates (VS):

```bash
Transient's Predicted Classification: VS
Suggested Associations:
+-------------------+-------+------------+-----------------------+----------------------+------------------------+---------------------------+-------------+--------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
| association type  | rank  | rankScore  | catalogue table name  | catalogue object id  | catalogue object type  | catalogue object subtype  | raDeg       | decDeg       | separationArcsec  | physical separation kpc  | direct distance  | distance  | z     | photoZ  | photoZErr  | Mag    | MagFilter  | MagErr  | classification reliability  | merged rank  |
+-------------------+-------+------------+-----------------------+----------------------+------------------------+---------------------------+-------------+--------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
| VS                | 1     | 1003.31    | 2MASS/PS1/GAIA        | 00052789-2852382     | star                   | multiple                  | 1.366236    | -28.877295   | 1.31              |                          |                  |           |       |         |            | 16.39  | r          | 0.00    | synonym                     |              |
| VS                |       | 1003.31    | 2MASS PSC             | 00052789-2852382     | star                   |                           | 1.366236    | -28.877295   | 1.31              |                          |                  |           |       |         |            | 14.45  | J          | 0.06    | synonym                     | 1            |
| VS                |       | 1003.31    | PanSTARRS DR1         | 73340013663207570    | galaxy                 |                           | 1.36621403  | -28.8772702  | 1.35              |                          |                  |           |       |         |            | 16.39  | r          | 0.00    | synonym                     | 1            |
| VS                |       | 1003.31    | Gaia DR2              | 2321035377987494528  | star                   |                           | 1.36625778  | -28.8772455  | 1.50              |                          |                  |           |       |         |            | 18.20  | G          |         | synonym                     | 1            |
+-------------------+-------+------------+-----------------------+----------------------+------------------------+---------------------------+-------------+--------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
FINISH RANKING/START UPDATING TRANSIENT DB: 0
FINISH UPDATING TRANSIENT DB/START ANNOTATING TRANSIENT DB: 0
The transient is synonymous with <em>00052789-2852382</em>; a J=14.45 mag stellar source found in the 2MASS/PS1/GAIA catalogues. It's located 1.3" from the stellar source core.
``` 

The transient was matched **synonymously** with the source above as these coordinates lie almost on top of the source. Hence the VS classification. The catalogued source just peaks above a brightness limit in the PS1 i-band causing synonymous transients to be considered as variable stars even though the catalogued source is set to 'galaxy;.

There are also the [mean coordinates reported on the object webpage](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1000527920285242200/) which are slightly different from the `tcs_latest_object_stats`

RA: 1.36628   
DEC: -28.87783  

Running Sherlock against these coordinates gives a SN classification:

```bash
Transient's Predicted Classification: SN
Suggested Associations:
+-------------------+-------+------------+---------------------------+----------------------+------------------------+---------------------------+-------------+--------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
| association type  | rank  | rankScore  | catalogue table name      | catalogue object id  | catalogue object type  | catalogue object subtype  | raDeg       | decDeg       | separationArcsec  | physical separation kpc  | direct distance  | distance  | z     | photoZ  | photoZErr  | Mag    | MagFilter  | MagErr  | classification reliability  | merged rank  |
+-------------------+-------+------------+---------------------------+----------------------+------------------------+---------------------------+-------------+--------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
| SN                | 1     | 2005.00    | 2MASS/PS1/GAIA/GLADE      | 00052789-2852382     | star                   | multiple                  | 1.366408    | -28.877411   | 1.52              |                          |                  |           |       |         |            | 16.39  | r          | 0.00    | association                 |              |
| VS                |       | 2005.00    | 2MASS PSC                 | 00052789-2852382     | star                   |                           | 1.366236    | -28.877295   | 1.85              |                          |                  |           |       |         |            | 14.45  | J          | 0.06    | association                 | 1            |
| SN                |       | 2005.00    | PanSTARRS DR1             | 73340013663207570    | galaxy                 |                           | 1.36621403  | -28.8772702  | 1.95              |                          |                  |           |       |         |            | 16.39  | r          | 0.00    | association                 | 1            |
| VS                |       | 2005.00    | Gaia DR2                  | 2321035377987494528  | star                   |                           | 1.36625778  | -28.8772455  | 2.03              |                          |                  |           |       |         |            | 18.20  | G          |         | association                 | 1            |
| SN                |       | 2005.00    | 2MASS XSC                 | 00052793-2852386     | galaxy                 |                           | 1.366408    | -28.877411   | 1.52              |                          |                  |           |       |         |            | 13.89  | J          | 0.07    | association                 | 1            |
| SN                |       | 2005.00    | The GLADE Catalogue v2.3  | 198789               | galaxy                 | G                         | 1.366408    | -28.877411   | 1.52              |                          |                  |           |       |         |            | 16.71  | B          |         | association                 | 1            |
+-------------------+-------+------------+---------------------------+----------------------+------------------------+---------------------------+-------------+--------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
FINISH RANKING/START UPDATING TRANSIENT DB: 0
FINISH UPDATING TRANSIENT DB/START ANNOTATING TRANSIENT DB: 0
The transient is possibly associated with <em>00052789-2852382</em>; a B=16.71 mag stellar source found in the 2MASS/PS1/GAIA/GLADE catalogues. It's located 1.90" S, 0.00" E from the stellar source centre.
```

The transient was matched in **association** with the the sources above as these webpage coordinates now lie a little removed from the underling catalogued sources, and hence look more like a SN.

Re-adding a general synonymous match as 'SN' instead of 'NT' has solved the issue. All 3 transients reported in this issue are now classified as SN.

**Comment by thespacedoctor** [comment]
Fix/tweaks to algorithm propagated to atlas and lasair. Watch out for too many true VS getting into eyeball lists - if this happens please reopen this issue (or a new issue) with some examples.

**Comment by thespacedoctor** [comment]
Reopening. Here's an example of a classification where Sherlock latches onto a Gaia source. Transient is classified as a VS as it is 'synonymous' with underlying Gaia source. No other synonyms are found to override the classification:

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1103715460413730200/

Need a broader rethink for these kinds of classifications. Rethink pending ....

**Comment by mFulton07** [comment]
Here is an example of misclassification with an SDSS source:

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1000005230051237300/

**Comment by thespacedoctor** [comment]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1110216461442006800/

**Comment by thespacedoctor** [comment]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1232913370020543100/

**Comment by thespacedoctor** [comment]
There are 10 transients in total reported here and are all the result of the same issue; the transient is exactly coincident with an underlying source that has been previously assigned as a stellar identification in GAIA, SDSS or 2MASS. The 2 changes that fixed the bulk of these issue where to remove the *synonym* classification type from closely matched Gaia and 2MASS 'point sources'. Loosening the classification type to *association* allows the search to continue to other galaxy catalogues and ranking of the final results may rank galaxy matches higher. There is a danger here that many true stellar sources will end up being mis-associated with nearby galaxies, but I think the inclusion of the PS1 and SDSS catalogues offset these risks as they have much more robust star-galaxy separation than Gaia and SDSS and therefore transients synonymous with stars in these catalogue will be blocked from progressing to the next stage of galaxy matching.

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1000005230051237300/>  
20.74 mag stellar source found in the SDSS catalogue. It's located 1.81" N, 0.68" E from the stellar source centre.  
**FIXED**: reduced SDSS VS association in this magnitude range from 2.5 arcsec to 2 arcsec  

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1010851411170309300/>   
Previously fixed  

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1083845560144048900/> 
G=19.25 1.5" from the stellar source core    
**FIXED**: only allow Gaia sources to be added as associations not synonyms, this allows search to continue to other galaxy catalogues and ranking of the final results may rank galaxy matches higher.

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1103504551463338600/>   
G=18.92 mag stellar source 0.6" from the stellar source core  
**FIXED**: only allow Gaia sources to be added as associations not synonyms.

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1103715460413730200/>    
G=18.68 mag stellar source found in the GAIA catalogue. It's located 1.1" from the stellar source core.  
**FIXED**: only allow Gaia sources to be added as associations not synonyms.  

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1110216461442006800/>    
J=14.80 mag stellar source found in the 2MASS catalogue. It's located 1.5" from the stellar source core.  
**FIXED**: reduced SDSS VS association in this magnitude range from 2.5 arcsec to 2 arcsec  (2MASS star also found in SDSS)

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1122254931154928600/>     
G=18.03 mag stellar source found in the GAIA catalogue. It's located 0.1" from the stellar source core.  
**FIXED**: only allow Gaia sources to be added as associations not synonyms.  

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1140601601124650600/>    
J=16.70 mag stellar source found in the 2MASS catalogue. It's located 0.4" from the stellar source core.    
**FIXED**: only allow 2MASS sources to be added as associations not synonyms, this allows search to continue to other galaxy catalogues and ranking of the final results may rank galaxy matches higher.

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1165812961020703100/>    
J=15.15 mag stellar source found in the 2MASS/GAIA/PS1 catalogues. It's located 0.5" from the stellar source core.  
**FIXED**: only allow 2MASS sources to be added as associations not synonyms.  

<https://star.pst.qub.ac.uk/sne/atlas4/candidate/1232913370020543100/>    
J=16.45 mag stellar source found in the 2MASS catalogue. It's located 1.2" from the stellar source core.
**FIXED**: only allow 2MASS sources to be added as associations not synonyms.  

I will push algorithm changes to ATLAS, Lasair and PanSTARRS systems shortly.

**Comment by thespacedoctor** [comment]
Fixes have now been rolled out across all sherlock instances.
