### ISSUE TITLE
Seemingly obvious SN candidate classified as ORPHAN

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#121]
This object was classified as an ORPHAN by Sherlock.

There's definitely a PS1 source nearby and the PS1 imagery shows a clear galaxy.  Curious to know how it got an ORPHAN classification.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1000749640184852800/

**Comment by thespacedoctor** [comment]
A search within 5 arcsec on the MAST archive on the PS1 DR1 **mean objects** tables yields a match:

[![](https://live.staticflickr.com/65535/51118823999_c1abf5e860_b.jpg)](https://live.staticflickr.com/65535/51118823999_c1abf5e860_b.jpg)

But the same search on the **stacked objects** tables (same data we have in the Sherlock database) returns nothing!

[![](https://live.staticflickr.com/65535/51119868665_ccdd864473_b.jpg)](https://live.staticflickr.com/65535/51119868665_ccdd864473_b.jpg)

The same is true for PS1 DR2. Note `ndetections` for this object is 2, so my take on this is that there was not enough PS1 data in this area to go into making a stack. I'm also not sure I would blindly trust PS1 mean object data with less than 3 detections.

Take-away here is that this is a catalogue issue and not a Sherlock algorithm issue.

On a positive note, running Sherlock with the NED flag switched on finds a match:

> The transient is possibly associated with <em><a href="https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=WISEAJ000749.68-184842.6&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES">WISEAJ000749.68-184842.6</a></em>; a 17.21 mag galaxy found in the NED catalogue. It's located 7.70" S, 1.00" W from the galaxy centre.
