### ISSUE TITLE
Object misclassified as star in ATLAS (but not Pan-STARRS)

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#123]
This object was misclassified as VS in ATLAS, but SN in Pan-STARRS.  (Probably to do with the mean coordinates.)

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1210319160123442400/
https://star.pst.qub.ac.uk/sne/ps13pi/psdb/candidate/1210319230123444000/

**Comment by thespacedoctor** [comment]
Even with the earliest ATLAS detection coordinates, Sherlock is now getting this correct:

> The transient is possibly associated with <em><a href="http://skyserver.sdss.org/dr12/en/tools/explore/Summary.aspx?id=1237666183472808439">SDSS J210319.2-123442.5</a></em>; a J=15.75 mag galaxy found in the SDSS/2MASS/PS1 catalogues. It's located 0.18" S, 1.61" W from the galaxy centre.
