### ISSUE TITLE
Association with a star at 4.67 arcsec - which is too far. But maybe an edge case ?

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#125]
This is associated with a G = 18.45 star 

https://lasair.roe.ac.uk/object/ZTF20achwhfm/

But it is 4.67 arcsec away -  too far to be astrometrically coincident. 

Although Sherlock does say "possibly" associated and (correctly) does not classify it as a synonym.  Was this ~5 arcsec match to catch high PM stars ? 

That's a little bit too far - but maybe this is  an edge case. Not sure if bug or not !!

**Comment by thespacedoctor** [comment]
The radius was set to 5" ... unclear as to why I set it so high, wasn't for HPM stars. Officially a bug I think. I've updated all algorithms to use 2.5".
