### ISSUE TITLE
Fast track object missed by Sherlock

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#126]
I've been cleaning out the PS1 list and spotted this, which is a clear fast track object (z=0.0178)
https://star.pst.qub.ac.uk/sne/ps13pi/psdb/candidate/1223248931391237400/

It was originally spotted and promoted by PS2 (in August), but its significance was missed!
https://star.pst.qub.ac.uk/sne/ps23pi/psdb/candidate/1223248931391237300/

Also in ATLAS with same Sherlock context.
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1223248891391237500/

Sherlock has had several algorithm updates since this object was promoted to the Eyeball List, so may have been fixed already.

**Comment by thespacedoctor** [comment]
Today Sherlock would have correctly placed this in the fast-track list:

> The transient is synonymous with <em>UGC12075</em>; a W1=13.24 mag galaxy found in the LASR catalogue. It's located 1.0" (0.4 Kpc) from the galaxy core. A host distance of 80.3 Mpc (z=0.018) implies a <em>m - M =</em> 34.52.
