### ISSUE TITLE
ATLAS VS - should be SN

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#129]
Spotted this in PS2 this evening.  But there's a whole lightcurve in ATLAS.  Not sure why it would have got a VS classification in ATLAS.  (Correct classification in PS2.)  Probably skewed by the first few detections in ATLAS.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1032849441371521900/
https://star.pst.qub.ac.uk/sne/ps23pi/psdb/candidate/1032849201371522800/

**Comment by smarttgit** [comment]
here's one in NED galaxy at z = 0.04. Sherlock gets it right in classification, but the context text notes it is a star 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1032216080334918300/
Erroneously in the Gaia catalogue and I think in the 2MASS point source
And the context text describes it as a star - although the Sherlock classification is correct !!

**Comment by thespacedoctor** [comment]
Ken's source is now correct:

> The transient is possibly associated with <em>03284928+3715220</em>; a J=16.50 mag galaxy found in the 2MASS/PS1 catalogues. It's located 0.02" S, 2.01" E from the galaxy centre.

And with a little adjusting of catalogue weighting so too is Stephen's:

> The transient is possibly associated with <em>03221614-3349179</em>; a J=14.18 mag galaxy found in the 2MASS/GAIA catalogues. It's located 0.09" S, 0.82" W from the galaxy centre.
