### ISSUE TITLE
Object misclassified as an orphan

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#130]
Not sure why this is an "orphan".  Almost on top of PS1 and Gaia source!

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1000707411372730000/

**Comment by smarttgit** [comment]
Probably proper motion

**Comment by thespacedoctor** [comment]
Latest version of sherlock now catching this as a VS:

> The transient is possibly associated with <em>NBH7003482</em>; a V=17.53 mag stellar source found in the GSC/2MASS/PS1/GAIA catalogues. It's located 0.41" S, 1.96" E from the stellar source centre.

even using the original ATLAS first detection coordinates:

> The transient is possibly associated with <em>2877622973015526656</em>; a G=17.09 mag stellar source found in the GAIA/PS1 catalogues. It's located 0.95" S, 2.11" E from the stellar source centre.
