### ISSUE TITLE
Misleading Annotations

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/sherlock#131]
http://pessto.org/marshall/transients/41404338

>  SN - The transient is possibly associated with N2P4000693; a V=13.30 mag stellar source found in the GSC/2MASS/PS1/GAIA catalogues. It's located 1.06" S, 1.80" W from the stellar source centre.

The underlying source is flagged as a galaxy in PS1 but star in Gaia. SN classification given but annotation referencing association as stellar. 

Make sure classification and annotation are self-consistent.

**Comment by smarttgit** [comment]
Also here : 

Classified as SN, but is bright star (in Gaia) 
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1184208900081831600/

**Comment by thespacedoctor** [comment]
http://pessto.org/marshall/transients/41404338

[![](https://live.staticflickr.com/65535/51104607397_53c9747a95_z.png)](https://live.staticflickr.com/65535/51104607397_53c9747a95_o.png)

Unlike GAIA DR2 and PS1 DR1, which both have distinct entries for the 2 sources, it also looks like these 2 stellar source are blended in GSC v2.3 and 2MASS, shifting the central coordinate of the recorded catalogue entry. This in turn has confused Sherlock when trying to merge the cross-catalogue entries for the 2 sources causing Sherlock to also blend them into one source! PanSTARRS DR1 has the (clear stellar) source to the south of the transient flagged as a galaxy, and hence the a SN designation but association with a (blended) stellar source.

The solution here is to allow Sherlock to maintain the deblending accuracy of more the recent survey catalogues during the association merging stage.

Reducing the source merging radius from 3 arcsec to 1 arcsec (1/9th of the original matching area) has broken the link between the 2 sources in this case. 

---

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1184208900081831600/

With this second source Sherlock gets the annotation correct with the most recent mean coordinates (280.53685,-8.30793) on the ATLAS pages, flagging the transient as a VS.

Using the first detection coordinates (280.537,-8.3088) Sherlock returns the mismatched SN classification with a stellar source. The associated stellar source is marked as a star in Gaia DR2 but a galaxy in PS1 DR1. As the coordinates are far from the stellar core, the transient is flagged as associated (not synonymous) with the source and therefore given a BS classification with GAIA but SN with PS1. SN trumps BS.

The solution here was to use catalogue quality weights *within* the merged source sets to sort the data (currently only used to compare merged sets). 

This source now gets a VS classification even with the offset first detection coordinates.

---

Finally, I have fixed the original annotation mismatches. If SN then the underlying sources identified as a galaxy in the annotation.
