### ISSUE TITLE
Sherlock probable host correct, but host has a spectrum

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#132]
Just a minor issue.  Sherlock got the host correct, but there's a spectrum in NED that got missed by Sherlock.  Could be because we're not cacheing NED data?

https://star.pst.qub.ac.uk/sne/ps13pi/psdb/candidate/1080544200033311400/

**Comment by thespacedoctor** [comment]
Yes this is a caching issue. I need to write a separate NED downloader at some point that runs continuously to update the local cache.
