### ISSUE TITLE
Sherlock misses 100Mpc fast track object - has there been a change ?

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#133]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1130133181274953400/

Should be associated with NGC4293 - about 25 kpc south of this galaxy at z = 0.018. 

Not sure why it associates with the faint source in PS1 i = 22.2 galaxy at about 4" away. 

Has something changed in Sherlock recently, usually we get these associated with the nearby galaxy (since we have a lot of false positives, which we expect and accept).

**Comment by smarttgit** [comment]
Similar result in Lasair - so Sherlock versions similar as expected : 
https://lasair.roe.ac.uk/object/ZTF21aasuego/

**Comment by smarttgit** [comment]
But in PESSTO - it gets correctly associated ! 
http://www.pessto.org/marshall/transients/search?q=AT2021inl

**Comment by thespacedoctor** [comment]
The PS1 module in the yaml algorithms in ATLAS, PanSTARRS and Lasair were slightly behind the version for the Marshall which I have been using during debugging. I think these are actually part of the issues resolved in #131. I've updated the algorithms for PS1 and ATLAS now. @genghisken could you handle the Lasair yaml file updates or should I ask Gareth?

**Comment by thespacedoctor** [comment]
All systems are now up-to-date with Sherlock v2.1.8
