### ISSUE TITLE
VS misclassification

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#136]
Any idea why this one got classified as a VS?  There doesn't seem to be a star nearby...
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1183704161334914200/
This is a "fast track" object picked up by ZTF.

**Comment by thespacedoctor** [comment]
Turning off the synonym match break fixes this (see issue #127)

![gitscout-image-from-clipboard-1](http://static.gitscout.com/3d9d7698c320d0e3a3e0d53919fe3fc0f7438a2432991f1441cf0899f16400e0.png)
