### ISSUE TITLE
 Ranking issue triggered by the other spatially nearby hosts

### ISSUE THREAD

**Issue by mFulton07** [thespacedoctor/sherlock#138]
https://psweb.mp.qub.ac.uk/sne/ps13pi/psdb/candidate/1134425051202508200/.

It seems Sherlock got confused by the nearby sources and has mis-ranked the big galaxy at z = 0.027.

**Comment by thespacedoctor** [comment]
Hard to do much about this one. If knot in the nearby galaxy (UGC 08691), which is identified as a distinct galaxy in both SDSS and 2MASS, was in fact a background galaxy then we would be claiming Sherlock got it right. Problem here lies in the underlying catalogue data and is tricky/impossible for Sherlock to get the top rank association correct 100% of the time with these cases. Happy to receive creative suggestions to better the matching/ranking.
