### ISSUE TITLE
GALEX ASC sources result in "?" classification - most likely "SN"

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#15]
The GALEX sources found through NED (“GALEXASC” == GALEX all sky catalogue sources) are mostly galaxies - sherlock classifies these associations with a  “?"

These are nearly all "SN"

There may be some CVs or variables lurking in the GALEXASC, but safest to use this as a galaxy catalogue. All the sources I've looked at are galaxies

**Comment by thespacedoctor** [comment]
GALEX UvS sources in NED have been moved to the `tcs_view_galaxy_ned_stream` database view and out of the `tcs_view_other_ned_stream`, i.e. transients associated with these sources now get a `SN` designation.

**Comment by thespacedoctor** [comment]
For stephen's source:

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1022421090264826800/

I tweaked the classification ranking code to reduce the weight of galaxy-associated sources physically far from the host cores (just enough to allow variable stars to float to rank 1). This worked nicely to correct this source so it's now assigned VS status.

I think Owen source must have been corrected with issue #27

**Comment by thespacedoctor** [comment]
done
