### ISSUE TITLE
Few bugs 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#16]
- [x] LSQ16aab - marshall records host galaxy redshift (0.137) which is correct, but classifies it as orphan and doesn’t link to the 2MASS host

- [x] AT2016aqc - when you click on context, there is no table. Too many sources linked, can’t see what’s there ! Confusing. Maybe that’s why table doesn’t appear ?
The context is SN/Variablestar/?
But this should be unambiguous - there is a host galaxy with a redshift. So should just be "SN"

- [x] LSQ16yb - most likely is the AGN. If within 2” of known AGN then label it AGN (has 4 possibilities)

- [x] LSQ16abw - should be orphan. It is ”?”  .

**Comment by thespacedoctor** [comment]
All bug raised in this issue have been corrected - closing
