### ISSUE TITLE
No year specified in example bibtex entry

### ISSUE THREAD

**Issue by jamesgillanders** [thespacedoctor/sherlock#163]
There is a bibtex entry that references a zenodo link you want cited if people reference sherlock:

```
@software{Young_sherlock,
    author = {Young, David R.},
    doi = {10.5281/zenodo.8038058},
    license = {GPL-3.0-only},
    title = {{sherlock}},
    url = {https://github.com/thespacedoctor/sherlock}
}
```

This is missing a year (and month) entry -- on the zenodo page, this sherlock update is from 2023. I'd suggest adding the year to the bibtex entry on your github. For example:

```
@software{Young_sherlock,
    author = {Young, David R.},
    year = 2023,
    month = jun,
    doi = {10.5281/zenodo.8038058},
    license = {GPL-3.0-only},
    title = {{sherlock}},
    url = {https://github.com/thespacedoctor/sherlock}
}
```

Could also update to the newest version (v2.2.0, from August 2023)...

**Comment by thespacedoctor** [comment]
I've added a release date to the citation file. The year should appear now.
