### ISSUE TITLE
First pass through the Sherlock checks on PS1 data - comments and corrections

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#26]
Star, clearly but classed as SN 
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1094132471265316100/
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1093142871183336500/

----------

These should be NT,  but classed as SN 
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1093641271600056100/
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1093117021533803600/
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1092159711555725700/
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1094819311322800600/

This is classed as NT. But the galaxy is too faint to make the judgement that the transient is "nuclear".  Should be SN 
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1100840331481456600/
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1095252951565307300/

here's the pseudo-code I would use 
if host_mag < 21 then never use NT, always use SN, no matter what the separation

----------

Should be orphan. Classed as SN. But no obvious association. 
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1093031601384323100/
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1094659261241219300/

These are classed as "?" But I'd prefer "orphan" if there is no contextual  match 
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1082717621700310600/
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1072532131725709000/
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1065919011741247900/ 

Two of the last three are actually in  Galaxies detected in PS1 (outside SDSS footprint)  but we will need a way to ping PS1 catalogue and do star/gal separation. Not now, but will do in future)

----------

This is classed as SN, but should be QSO 
http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1100621341485244400/

Since there is an SDSS spectrum (see red box on SDSS cutout) - this comes from BOSS. Are these not in milliquas yet ? There must be a catalogue of BOSS QSOs. Since we see many. 

--------

This one doesn't have anything as a label 

http://psweb.mp.qub.ac.uk/sne/ps1gw/psdb/candidate/1095614411380542300/

**Comment by thespacedoctor** [comment]
Yes - don't trust the classifications as yet, I need to tweak ranking algorithm. Currently I've hit a bottleneck with the NED downloader. I need to download NED info for ~3,000,000 transient locations  before the search runs on the PS1 GW database. Sherlock is stupidly hitting NED once for each of the transient locations, which was fine for the PESSTO Marshall, but not for ATLAS and PS1. I've plan to speed this up which I'm currently implementing.

After this I will fine tune the algorithm

**Comment by thespacedoctor** [comment]
All of these but have been addressed in other issues
