### ISSUE TITLE
Not cross matching with SDSS over GSC 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#27]
Should first have picked up SDSS star, not the GSC object 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1072339581263703200/

Probable bug

**Comment by smarttgit** [comment]
And this one 
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1065618891300020800/

**Comment by smarttgit** [comment]
And this one - similar thing. It picks up the 2MASS galaxy 10" away, but not the stellar source which it is coincident with 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1053742981265912400/

**Comment by thespacedoctor** [comment]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1072339581263703200/

For this one here are the current matched results in the database:

![screengrab][screengrab 37930250052]

[screengrab 37930250052]: https://farm5.staticflickr.com/4454/37930250052_20eaeccf60_o.png 

The SDSS star is 1.9'' away from the *current* mean ATLAS RA/DEC. The current match tolerance for SDSS stars is 2.0''. My feeling is that the initial ATLAS position was outside of this match and it has now moved in with more observations.

**ACTION**: extend all PS searches to 2.5'' (ATLAS pixel size + a little). Give Gaia a higher weight than GSC. 

---

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1065618891300020800/

Possibly the same issue as before with SDSS matching tolerance.

---

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1053742981265912400/

This one is not in SDSS, but Gaia matches it. **ACTION:** adjust algorithm to give Gaia a better weight.

![screengrab][screengrab 37251492204]

[screengrab 37251492204]: https://farm5.staticflickr.com/4482/37251492204_0e267ef8a8_o.png

**Comment by smarttgit** [comment]
Agree !

**Comment by thespacedoctor** [comment]
The actions to give the Gaia catalogue a higher weight and to open out the point-source search radii to 2.5" has worked to correct the classifications of all stars reported in this issue. I am going to clear out the ATLAS eyeball list classifications and re-run sherlock with these changes now.
