### ISSUE TITLE
Change of catalogue

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#29]
Before we even get to the upgrade to Gaia+PS1

I think we need to consider just replacing GSC with PPMXL

"PPMXL is a combination of the data from the USNO-B1.0 and the infrared 2MASS catalog. It aims to be complete from the brightest stars down to about magnitude V=20 full-sky. PPMXL contains about 910,468,710 objects, and therefore is the largest collection of ICRS positions and proper motions at present."
 
http://dc.zah.uni-heidelberg.de/ppmxl/q/cone/info

I think USNO B1 is more reliable than GSC, but this PPMXL looks better

**Comment by thespacedoctor** [comment]
Finished reading papers and documentation for PPMXL.

There is **NO** flag to separate stars from galaxies, and it clear contains a bunch of galaxies:

> 900 million stars and galaxies

**Comment by thespacedoctor** [comment]
Now I have PPMXL installed I will run Sherlock on the good list sources in the ATLAS database to see if any match against PPMXL source. This should give us a very rough idea of how much the galaxy contamination will affect us.

**Comment by thespacedoctor** [comment]
Given the lack of star-galaxy separation info in PPMXL I think it may be best to wait the release of GAIA DR2 (25th April) and hope it has clear extended source metrics. Unfortunately this does not look hopeful ATM as their data release model draft has no direct mention of this kind of metric.

<https://www.cosmos.esa.int/web/gaia/dr2>

It does have crossmatching to PS1 catalogues (among others) which does have morphology info.

**Comment by thespacedoctor** [comment]
Gaia DR2 and PS1 now added
