### ISSUE TITLE
Saturated stars incorrectly labelled as galaxies in SDSS catalogues

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#38]
Some transients which are obviously stars are getting tagged as SN.  See, for example

[star1](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1103752021220705500/)
[star2](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1005418810384018800/)
[star3](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1103752021220705500/)
[star4](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1092424961220347100/)
[star5](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1081155620344549600/)
[star6](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1154539890161421500/)

Some recent parallel processing changes or changes to the synonym from 0.5 to 1.5 for NT may have triggered this.

**Comment by thespacedoctor** [comment]
This is a catalogue level issue - 4 of the 6 are saturated stars flagged as galaxies in SDSS. E.g.

<http://skyserver.sdss.org/dr14/en/tools/chart/navi.aspx?ra=159.466736471&dec=22.1183929412&scale=0.5&width=500&height=500&opt=GPS>

**Comment by thespacedoctor** [comment]
Changed the title - this catalogue-level issue could possibly be worked around in the algorithm

**Comment by genghisken** [comment]
How about these:

[star7](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1093032911365123600/)
[star8](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1011733990380321300/)
[star9](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1011635050380600600/)

**Comment by thespacedoctor** [comment]
stars 2, 5, 7, 8, 9 now correctly flagged as VS.

The misclassification of sources was the result of some debugging Ken and I were doing last week while installing an update to Sherlock on PSDB3. The crossmatches and classifications should have been cleared out and Sherlock reran once the update was complete, but they weren't, leaving incomplete/erroneous classifications in the eyeball list.

Sherlock is now rerunning on all sources in the ATLAS eyeball list and correct classifications are now being populated.

I'm leaving this issue open as I still have to try and mitigate the SDSS saturated galaxy issue (stars 1, 3, 4 & 6)

**Comment by smarttgit** [comment]
To mitigate the erroneous SDSS classification of a galaxy (when it really is a bright star) - is it not simple for the algorithm to stop when it finds a synonymous match with a bright star, and not progress to SDSS ? These are cases were the star is probably brighter than 10-12 mag. 

So it should get a VS flag earlier in the algorithm

**Comment by thespacedoctor** [comment]
So of the 4 SDSS 'galaxy' transients, one is now correctly flagged as a VS:

[star4](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1092424961220347100/)

The other 3 are flagged as NTs as they are 'synonymous' with the SDSS 'galaxies' with separations of 0.6", 0.9" and 1.3":

[star1](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1103752021220705500/)
[star3](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1103752021220705500/)
[star6](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1154539890161421500/)

Note before increasing the NT association radius from 0.5" to 1.5" these would correctly have been flagged as VS. Also remember that GSC has some bright nearby galaxies flagged as point-sources (the opposite of the SDSS problem). Giving 2MASS PSC/PPMXL a higher ranking than SDSS at the bright end is probably our solution here.

**Comment by thespacedoctor** [comment]
turns out this *was* a simple fix. I changed the algorithm so that transients in  bright galaxies (< 15 mag) in the SDSS Photoobjall table are *always* only 'associated' with the galaxy. Previously if a transient was in the core of the bright SDSS Photoobjall galaxy it was given the `NT` designation and treated as 'synonymous' thereby increasing it's classification-accuracy ranking. 

Stars 1, 3, and 6 now correctly given VS status.

Note, if the matched catalogue source truly is a galaxy then it will be in NED/NED-D/SDSS SpecObjAll and core-transients correctly given 'NT" status anyway.

**Comment by thespacedoctor** [comment]
Issue from @smarttgit :

Some objects labelled as NT, but these are big bright stars.

SDSS has spurious "galaxy" entries on top of big fat stars.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1092830961113548600/

Need a way of pulling out the bright stars as very highly weighted

**Comment by smarttgit** [comment]
This is now sorted with the bug fixes and other enhancements Dave has done
