### ISSUE TITLE
Wrong association - obvious star

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#39]
This is obvious synonymous with R=14 mag star

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1022421090264826800/

But sherlock classifies as a SN because of small GALEX source 3 mins away

Something wrong in decision tree 

Many of these - contributing to the drowning in VS objects

**Comment by OMcBrien** [comment]
I've found a star here that sherlock has classified as a SN. Context info associates it with the GSC though, so there isn't a galaxy there in the first place.

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1110418750054716200/

GSC was causing problems before but for things sherlock classifies as UNCLEAR. I'll link a few more of these as I find them.

**Comment by thespacedoctor** [comment]
For stephen's source:

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1022421090264826800/

I tweaked the classification ranking code to reduce the weight of galaxy-associated sources physically far from the host cores (just enough to allow variable stars to float to rank 1). This worked nicely to correct this source so it's now assigned VS status.

I think Owen source must have been corrected with issue #27
