### ISSUE TITLE
Incorrectly classified 'orphans'

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/sherlock#54]
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1163011960401532700/
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1175638670203248700/

bad "orphans"

**Comment by genghisken** [comment]
Another "orphan" here - possibly because very bright.
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1051800440173029600/

**Comment by smarttgit** [comment]
Quite a few of these - definite star coincidence, but not caught as star.

**Comment by smarttgit** [comment]
And similarly - some objects labelled as NT, but these are big bright stars. 

SDSS has spurious "galaxy" entries on top of big fat stars. 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1092830961113548600/

Need a way of pulling out the bright stars as very highly weighted

**Comment by smarttgit** [comment]
Seems quite common to completely miss the obvious bright star at the position of the transient. 

Not sure why this could be - could it be proper motions of the star ?

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1082004391533754600/

**Comment by thespacedoctor** [comment]
These incorrectly classified orphans are a result of a bug in HMpTy introduced a few weeks ago. See issue #61 for more details. Here are the now corrected classifications for these sources:

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1163011960401532700/   -- VS
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1175638670203248700/  -- SN
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1051800440173029600/  -- VS
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1045211360251138100/  -- VS
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1092830961113548600/  -- STILL NT
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1082004391533754600/  -- VS

Note the SDSS bright point-source masquerading as a galaxies is a separate issue. Reopening issue #38
