### ISSUE TITLE
NED infrared sources in the galactic plane

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#55]
Here's another one of those IR sources in the galactic plane from NED, which Sherlock classified as a SN.
https://star.pst.qub.ac.uk/sne/atlas4/candidate/1172541370302243600/

**Comment by thespacedoctor** [comment]
I've eyeballed ~50 sources that match against one of these IR sources from NED. Usually they are trumped by a Gaia DR1 stellar source detection. I agree that these sources are contaminating the 'SN' stream. Converting them to 'unclear'.
