### ISSUE TITLE
Links don't work to (at least some) NED galaxies 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#65]
I think this is a sherlock issue as the same bug on both sets of pages : 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1125036591141234300/

and 

http://www.pessto.org/marshall/transients/search?q=ATLAS18pbs

In the context commentary : 
"The transient is possibly associated with **SDSS J125036.28+141236.8;** a 22.40 mag galaxy found in the NED catalogue. It's located 1.80" S, 4.80" E from the galaxy centre."

Clicking on the link for the host galaxy  **SDSS J125036.28+141236.8**  does not link to the NED page for the host, I get  the banner error page : 

"The object name that you submitted is not currently recognized
    by the NED name interpreter."  .......

**Comment by smarttgit** [comment]
I checked some more- seems to be when the context picks a NED source that the links is broken. When it is an SDSS source, then the link to the SDSS page always seems to work.

**Comment by thespacedoctor** [comment]
Thanks - the NED links can be tricky to get correct as there are various nuances in the way names are formatted in the URL. 

Note to self:

I have encoded 'SDSS J125036.28+141236.8' as `SDSS%20J125036.28+141236.8` but the correct encoding to link in NED is `SDSS+J125036.28%2B141236.8`.

So spaces are encoded as `+` but + encoded as `%2B`

**Comment by thespacedoctor** [comment]
I fixed this some time ago.
