### ISSUE TITLE
GLADE needs some investigation

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#67]
I wonder is this is GLADE catalogue problem or the way in which we are interpreting the information in GLADE. 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1145423731731041800/

Says : 

Context info: The transient is possibly associated with 1368469; a B=15.70 mag galaxy found in the The GLADE Catalogue v2.3. It's located 0.84" S, 2.68" W (1.5 Kpc) from the galaxy centre. A host distance of 109.9 Mpc(z=0.025) implies a m - M = 35.153404.

In NED, the same galaxy is identified  as 2MASX J14542432+7310428  but there is no redshift in NED so how does GLADE get a distance ? Needs checking, maybe GLADE associates this iwth a galaxy group which does have a redshift ?

**Comment by smarttgit** [comment]
Also, GLADE is reporting wrong redshift 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1143427391313306700/

Galactic (l,b): (50.28971,67.17327)
Context info: The transient is possibly associated with 365260; a B=14.84 mag galaxy found in the The GLADE Catalogue v2.3. It's located 1.17" N, 2.18" W (1.6 Kpc) from the galaxy centre. A host distance of 130.8 Mpc(z=0.033) implies a m - M = 35.810638.

But the NED and SDSS redshifts are  consistent at z = 0.029290

So I wonder where GLADE is pulling this z from ?

**Comment by thespacedoctor** [comment]
First transient is [ATLAS18ojz](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1145423731731041800/). The matched Glade galaxy is 2MASX14542432+7310428 with a reported redshift of z=0.024594  ... but from where?

Glade is currently at v2.3 (this is also the version in Sherlock's database).

However Vizier hosts an older version of Glade (v1.2) and you can [find the record for the 2MASS galaxy in that catalogue here](https://vizier.u-strasbg.fr/viz-bin/VizieR-4?-ref=VIZ5e7522d85c3e&-to=-4b&-from=-2&-this=-4&%2F%2Fsource=VII%2F275&%2F%2Ftables=VII%2F275%2Fglade1&-out.max=50&%2F%2FCDSportal=http%3A%2F%2Fcdsportal.u-strasbg.fr%2FStoreVizierData.html&-out.form=HTML+Table&%2F%2Foutaddvalue=default&-order=I&-oc.form=sexa&-out.src=VII%2F275%2Fglade1&-nav=cat%3AVII%2F275%26tab%3A%7BVII%2F275%2Fglade1%7D%26key%3Asource%3DVII%2F275%26pos%3A14542432%2B7310428%28+++2+arcmin+J2000%29%26HTTPPRM%3A&-c=14542432%2B7310428&-c.eq=J2000&-c.r=++2&-c.u=arcmin&-c.geom=r&-source=&-source=VII%2F275%2Fglade1&-out=RAJ2000&-out=DEJ2000&-out=Dist&-out=Bmag&-out=BmagHyp&-out=ImagHyp&-out=modzHyp&-out=mod0Hyp&-out=logd25Hyp&-out=logr25Hyp&-out=logdcHyp&-out=PAHyp&-out=BmagHypC&-out=ImagHypC&-out=U-BHypC&-out=B-VHypC&-out=Jmag2&-out=Hmag2&-out=Kmag2&-out=a%2Fb&-out=PAK&-out=BmagGWGC&-out=maj&-out=min&-out=PAGWGC&-out=DistGWGC&-out=Kmag2MPZ&-out=Bmag2MPZ&-out=zsp2MPZ&-out=zph2MPZ&-out=Flag&-meta.ucd=2&-meta=1&-meta.foot=1&-usenav=1&-bmark=GET). Here we find that the redshift is in fact a photoz taken from the [2MASS Photometric Redshift catalogue (2MPZ)](http://ssa.roe.ac.uk/TWOMPZ.html). We can't by any stretch of the imagination view this as reliable distance estimate. 

![](https://live.staticflickr.com/65535/49680682686_01dd5cee4a_o.png)

Somewhere in the move from v1.2 to v2.3 many columns in the published Glade catalogue got consolidated and the source of distance measurements has been obscured. But we have [a flag in the catalogue](http://glade.elte.hu/Download.html) `flag2`:

![](https://live.staticflickr.com/65535/49680976007_b819fd0aa0_o.png)

Given the information gleaned from Vizier I think I can interpret the flag values as:

| Flag Value  | Meaning |
| :------------ | :----------- |
| 0     | no distance or redshift  |
| 1      | photoz - and distances are derived from photoz  |
| 2     | distance measurement - redshift derived from distance measurement  |
| 3     | specz - and distances are derived from specz  |

A query to the sherlock database gives me the following breakdown on flag values in Glade:

| flag value | count |
|-----------------|-----------|
| 0               | 540399    |
| 1               | 1124475   |
| 2               | 1556716   |
| 3               | 41291     |

The second transient is [ATLAS18opy](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1143427391313306700/) and matches against 2MASX14342755+3133070 in Glade. A quick look in the database shows again that flag2=1.

I think the action here is to disregard all distance measurements set for sources with flag2=1.

**Comment by thespacedoctor** [comment]
Updated the database catalogue with the following query:

```sql
UPDATE tcs_cat_glade_v2_3 
SET 
    dist_lum_mpc = NULL,
    dist_lum_mpc_err = NULL,
    redshift = NULL
WHERE
    dist_lum_flag = 1;
```
