### ISSUE TITLE
Sherlock picking up the wrong redshift but right galaxy

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#69]
Sherlock correctly associates this object (AGN, but rising) with UGC 8823, but sets z=1.0 instead of z=0.03

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1135303481691829500/

**Comment by thespacedoctor** [comment]
The top match for 'UGC 8823' was found in Milliquas v5.2. Unfortunately it appears the row for 'UGC 8823' was not imported correctly into the catalogues database; the redshift was append to a value in another column. 

[Version 5.3 of Milliquas is now out](https://heasarc.gsfc.nasa.gov/w3browse/all/milliquas.html), and I will try and fix the import issue when building that catalogue table.
