### ISSUE TITLE
Picking up an SDSS PhotoObj source rather than the real host with spec-z available

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#72]
https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1133604011661803700/

Picks up a SDSS PhotoObj which is a spurious object in SDSS, since it is part of the spiral arm structure. 

But Sherlock should be prioritising on the GLADE/NED host that has a spec-z

**Comment by smarttgit** [comment]
Same problem 
https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1235942761342041700/

**Comment by smarttgit** [comment]
Actually that's a slightly different issue, but it still should give priority to the spec-z host in NED

**Comment by thespacedoctor** [comment]
This is a nasty one. But both of these 'galaxies' have a `clean` flag = 0, meaning that the photometry is possibly unreliable.

![](https://farm2.staticflickr.com/1965/44467334105_4991cf8115_o.png)

Investigation of our local `sdss_photo_stars_galaxies_dr12` table reveals that 33.8% of ALL objects and 35.8% of photo-classified galaxies in this table have clean=0.

Currently in the good & confirmed lists we have 121 candidates that have a top-rank match of a galaxy from the SDSS photoObjAll table with clean=0 (and 381 with clean=1).

Once I cleared out the classifications and reran sherlock with the #64 fix this number dropped to 109.

Carefully inspecting each of these transient classification here are a list of issues I found:

- Transient matched against unrealistically faint galaxy in SDSS, better match to larger galaxy with greater angular sep:

  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1020844131024235700><
>  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1163612071210050700>

- Same galaxy in SDSS PhotoZ and in another catalogue with specZ but PhotoZ trumps specZ (note to self - a few found in NED angular phot-galaxy search not physical distance search):

  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1021714680051736500/>
  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1145332291030413900/>
  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1153559621464446000/>
  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1235942761342041700/>
  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1034806811495545400/>
  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1000254671032434800>
  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1022139441210030500/>

- SDSS photoZ smudge in galaxy matched over true galaxy (sometimes with indistinct core):

  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1030511330010443700/>
  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1172101641260907700/>
  <https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1223158481182028200/>

There are also cases where the ranking algorithm worked well with the transient correctly matched against a photoZ galaxy, but also close to a non-associated specZ galaxy:

<https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1015811190033220600/>  
<https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1101536081291738300/>  
<https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1231450620092440300/>  
<https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1232516151135602300/>  
<https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1234045941140602500/>  
<https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/1234552320035700000/>  



In general I think we now have the top-level sherlock *classification algorithm* (SN, VS, AGN ...) of transients working correctly in 99% of cases where a match is found - we just need to add more and more catalogues.

I now need to think clearly about updating the *crossmatch ranking algorithm* to best handle the above cases, where the decision to be made is about choosing the most likely host galaxy.



---

Here's the sequence of SQL commands I used to extract these example ...

Get good & confirmed-list objects with top-rank match in SDSS photoObjAll galaxies:

```sql
SELECT DISTINCT
    catalogue_object_id
FROM
    sherlock_crossmatches
WHERE
    transient_object_id IN (SELECT 
            id
        FROM
            atlas_diff_objects
        WHERE
            detection_list_id in (2,4))
        AND catalogue_view_name = 'tcs_view_galaxy_sdss_photo_stars_galaxies_dr12'
        AND rank = 1;
```

Match these ObjIDs against SDSS:

```sql
SELECT 
    clean, COUNT(*)
FROM
    crossmatch_catalogues.tcs_cat_sdss_photo_stars_galaxies_dr12
WHERE
    objID IN (1237665356155256866 , 1237674894738786453 ....... ) 
GROUP BY clean;
```

Grab the clean=0 ObjIDs:

```sql
SELECT clean, count(*) FROM crossmatch_catalogues.tcs_cat_sdss_photo_stars_galaxies_dr12 where type = 3 group by clean;

SELECT 
    objID
FROM
    crossmatch_catalogues.tcs_cat_sdss_photo_stars_galaxies_dr12
WHERE
    objID IN (1237665356155256866 , 1237674894738786453,
        .....) and clean=0;
```

Rematch against the good-list transients:

```sql
SELECT DISTINCT
    CONCAT('https://star.pst.qub.ac.uk/sne/atlas4/candidate_bs/',
            transient_object_id)
FROM
    sherlock_crossmatches
WHERE
    transient_object_id IN (SELECT 
            id
        FROM
            atlas_diff_objects
        WHERE
            detection_list_id = 2)
        AND catalogue_view_name = 'tcs_view_galaxy_sdss_photo_stars_galaxies_dr12'
        AND rank = 1
        AND catalogue_object_id IN (1237648675068969685 , 1237651249920083324 ....);


```

**Comment by thespacedoctor** [comment]
### New Ranking Algorithm

![](https://farm2.staticflickr.com/1950/45516628802_d586a149f1_o.png)

In many cases numerous sources from multiple catalogues are matched against the same transient. These matches are often different sources, but in some cases the same astrophysical source is listed across many catalogues with differing IDs.

The first job of the (new) ranking algorithm is to attempt to group together catalogue entries of the single sources. Once this grouping is done the matched sources need to be ranked in order of likelihood of being correctly associated with the transient.

The metrics that can are used to rank multiple potential associations are:

- Association Type ("AGN", "CV", "NT", "SN", "VS", "BS" ...)
- Physical Separation between source and transient locations
- Source Catalogue Accuracy (some catalogues are better than others)
- Angular Separation between source and transient locations

After the results are grouped into distinct astrophysical sources, a merged 'best-of' parameter-set is generated for each group. The best distance estimate/measurement is selected, all reported magnitudes are combined, the closest coordinate set to the transient location is used and the smallest transient-source angular separation converted to a physical distance separation.

If multiple classification are given for the group then the most accurate classification is selected from this ordered list: "AGN", "CV", "NT", "SN", "VS", "BS". For example if there are 3 entries for a distinct source with classifications "AGN", "NT" and "VS" then "AGN" is selected as the best classification.

Initial tests of the new ranking algorithm (ran against ATLAS good list) are looking promising  - please report any issues.

**Comment by thespacedoctor** [comment]
Fixed with the latest changes. Sherlock associates the the larger 48" distant galaxy as top ranked match:

```text
Transient's Predicted Classification: SN
Suggested Associations:
+-------------------+-------+------------+------------------------------+--------------------------------------------------+------------------------+---------------------------+-------------+------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
| association type  | rank  | rankScore  | catalogue table name         | catalogue object id                              | catalogue object type  | catalogue object subtype  | raDeg       | decDeg     | separationArcsec  | physical separation kpc  | direct distance  | distance  | z     | photoZ  | photoZErr  | Mag    | MagFilter  | MagErr  | classification reliability  | merged rank  |
+-------------------+-------+------------+------------------------------+--------------------------------------------------+------------------------+---------------------------+-------------+------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
| SN                | 1     | 2005.00    | NED                          | 2MASXJ01520575+3311231/WISEAJ015205.71+331123.5  | galaxy                 | multiple                  | 28.0239167  | 33.18983   | 48.14             | 77.33                    |                  | 390.52    | 0.09  |         |            | 11.30  | unk        |         | association                 |              |
| SN                |       | 2005.00    | NED                          | 2MASX J01520575+3311231                          | galaxy                 | G                         | 28.0239167  | 33.18983   | 48.14             | 77.33                    |                  | 390.52    | 0.09  |         |            | 11.30  | unk        |         | association                 | 1            |
| SN                |       | 2005.00    | NED                          | WISEA J015205.71+331123.5                        | galaxy                 | G                         | 28.0239167  | 33.18983   | 48.14             | 77.33                    |                  | 390.52    | 0.09  |         |            | 11.30  | unk        |         | association                 | 1            |
| SN                | 2     | 2005.00    | SDSS DR12 PhotoObjAll Table  | 1237678807996563768                              | galaxy                 | 3                         | 28.0389244  | 33.185582  | 5.50              | 33.90                    |                  | 2897.97   |       | 0.51    | 0.13       | 23.72  | r          | 2.10    | association                 |              |
+-------------------+-------+------------+------------------------------+--------------------------------------------------+------------------------+---------------------------+-------------+------------+-------------------+--------------------------+------------------+-----------+-------+---------+------------+--------+------------+---------+-----------------------------+--------------+
```
