### ISSUE TITLE
NULL (None) rank values in Sherlock for Lasair

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#75]
In the sherlock_crossmatches table for Lasair, the Rank values are NULL except for the top ranked crossmatch.  This could be a Lasair implementation issue, but raising it here first.

E.g.

https://lasair.roe.ac.uk/object/ZTF18acpdvos/

**Comment by thespacedoctor** [comment]
This is a feature. 

The short answer is **ONLY DISPLAY SOURCES WHERE RANK != NULL**, and the long answer ...

If you look carefully you'll see the crossmatched sources reported from all of the different catalogue are probably the *same* galaxy reported multiple times:

![](https://farm5.staticflickr.com/4879/45784551725_ecb025c0e8_o.png)

Sherlock does it's best to merge duplicates into one row (the top row in this case). There are 2 ranking columns call `rank` and `merged_rank`. For this object the values for those columns are given as:

```sql
select rank, merged_rank from sherlock_crossmatches where transient_object_id = "13516777"
```

![](https://farm8.staticflickr.com/7829/39734930993_98476cdf47_o.png)

`rank` gives the association rank for all *unique* matches (single source or set of duplicates) and `merged_rank` reports the rank that each individual catalogued row has been merged into. So in this case the top row reports the one *unique match* (rank = 1) and all of the catalogue rows reported for that match (merged_rank = 1).

I hope that's clear. Some more information can be found [here](https://github.com/thespacedoctor/sherlock/issues/72#issuecomment-433424132) ... but of course documentation would be better!
