### ISSUE TITLE
Conflicting distances for NGC 4622 reported by Marshall Sherlock vs ATLAS Sherlock

### ISSUE THREAD

**Issue by genghisken** [thespacedoctor/sherlock#76]
Tonight I promoted object ATLAS19bfk (AT2019so), which is in NGC 4622.  I know that this galaxy is at 65Mpc, and it's correctly reported in the ATLAS database (and agrees with NED).  But the Marshall reports that NGC 4622 is at 30Mpc.

**Comment by thespacedoctor** [comment]
The 30 Mpc is from NED-D galaxy catalogue from a direct distance measurement. I would trust this more than currently reported in NED.
