### ISSUE TITLE
Incorrect angular distance separation being calculated 

### ISSUE THREAD

**Issue by smarttgit** [thespacedoctor/sherlock#79]
Correct association, and angular offset, and redshift, but the conversion to physical distance out by factor ~100 or so 

Seems to be consistent problem - see these last few detections 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1025843851064907500/

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1174326011053818900/

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1153952130443544000/

**Comment by smarttgit** [comment]
Looks like this is an ATLAS interpretation of Sherlock problem - as Sherlock gets the calculation right 
in PESSTO marshall, but wrong on ATLAS pages 

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1130914640405438800/
http://www.pessto.org/marshall/transients/search?q=ATLAS19lsy

**Comment by thespacedoctor** [comment]
The 'direct distance scale' value (kpc/arcsec units) was incorrectly getting recorded as 'direct distance' (mpc units). This was only affecting reporting and not the algorithm filtering. Fix is tested and all entries in the non-garbage ATLAS lists have been corrected.

For the examples above:


https://star.pst.qub.ac.uk/sne/atlas4/candidate/1025843851064907500/  
259.9 Kpc -> 1.3 Kpc  

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1174326011053818900/  
4405.2 Kpc -> 21.2 Kpc  

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1153952130443544000/  
398.1 Kpc -> 1.9 Kpc  

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1130914640405438800/  
1898.1 Kpc -> 9.2 Kpc
