### ISSUE TITLE
quickstart table DB & tables for sherlock

### ISSUE THREAD

**Issue by QNWang93** [thespacedoctor/sherlock#86]
Hi 
I just started to learn about sherlock. Seems that installation (I built the develop version) doesn't put the basic DB and tables in local sql database(like the default quickstart DBs needed to be put in, and some other key tables like crossmatch_catalogues.tcs_helper_catalogue_tables_info are missing). I'm just wondering if there is a pack of necessary already-built DB and tables. That'll be really helpful!

**Comment by thespacedoctor** [comment]
Hi @QNWang93 The docs are really lacking at the minute - I apologise for that. I need to find the time to update them and build a robust quickstart database.
