### ISSUE TITLE
Install Sherlock in Mac system

### ISSUE THREAD

**Issue by XinyueSheng2019** [thespacedoctor/sherlock#94]
**I cannot install sherlock in Mac system. My Mac version is Mac Catalina 10.15.2. The errors are below:**

 ERROR: Command errored out with exit status 1:
   command: /Users/sherrysheng/opt/anaconda3/envs/sherlock/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-install-JD5mtR/HMpTy/setup.py'"'"'; __file__='"'"'/private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-install-JD5mtR/HMpTy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-wheel-8cttOt --python-tag cp27
       cwd: /private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-install-JD5mtR/HMpTy/
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-2.7
  creating build/lib.macosx-10.7-x86_64-2.7/HMpTy
  copying HMpTy/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
  copying HMpTy/__version__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
  copying HMpTy/cl_utils.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
  copying HMpTy/utKit.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
  creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
  copying HMpTy/htm/htm.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
  copying HMpTy/htm/_htmcCode.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
  copying HMpTy/htm/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
  copying HMpTy/htm/sets.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
  creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql
  copying HMpTy/mysql/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql
  copying HMpTy/mysql/conesearch.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql
  copying HMpTy/mysql/add_htm_ids_to_mysql_database_table.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql
  creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/commonutils
  copying HMpTy/commonutils/getpackagepath.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/commonutils
  copying HMpTy/commonutils/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/commonutils
  creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm/tests
  copying HMpTy/htm/tests/test_htm.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm/tests
  copying HMpTy/htm/tests/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm/tests
  copying HMpTy/htm/tests/test_sets.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm/tests
  creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql/tests
  copying HMpTy/mysql/tests/test_conesearch.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql/tests
  copying HMpTy/mysql/tests/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql/tests
  copying HMpTy/mysql/tests/test_add_htm_ids_to_mysql_database_table.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql/tests
  copying HMpTy/default_settings.yaml -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
  running build_ext
  building 'HMpTy.htm._htmc' extension
  creating build/temp.macosx-10.7-x86_64-2.7
  creating build/temp.macosx-10.7-x86_64-2.7/HMpTy
  creating build/temp.macosx-10.7-x86_64-2.7/HMpTy/htm
  creating build/temp.macosx-10.7-x86_64-2.7/HMpTy/htm/htm_src
  gcc -fno-strict-aliasing -I/Users/sherrysheng/opt/anaconda3/envs/sherlock/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sherrysheng/opt/anaconda3/envs/sherlock/lib/python2.7/site-packages/numpy/core/include -IHMpTy/include -IHMpTy/htm -IHMpTy/htm/htm_src -I/Users/sherrysheng/opt/anaconda3/envs/sherlock/include/python2.7 -c HMpTy/htm/htm_src/VarStr.cpp -o build/temp.macosx-10.7-x86_64-2.7/HMpTy/htm/htm_src/VarStr.o -arch i386 -arch x86_64
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  In file included from HMpTy/htm/htm_src/VarStr.cpp:14:
  HMpTy/htm/htm_src/VarStr.h:33:10: fatal error: 'iostream' file not found
  #include <iostream>
           ^~~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for HMpTy

ERROR: Command errored out with exit status 1:
     command: /Users/sherrysheng/opt/anaconda3/envs/sherlock/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-install-JD5mtR/HMpTy/setup.py'"'"'; __file__='"'"'/private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-install-JD5mtR/HMpTy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-record-9RwwVX/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-install-JD5mtR/HMpTy/
    Complete output (45 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-2.7
    creating build/lib.macosx-10.7-x86_64-2.7/HMpTy
    copying HMpTy/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
    copying HMpTy/__version__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
    copying HMpTy/cl_utils.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
    copying HMpTy/utKit.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
    creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
    copying HMpTy/htm/htm.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
    copying HMpTy/htm/_htmcCode.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
    copying HMpTy/htm/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
    copying HMpTy/htm/sets.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm
    creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql
    copying HMpTy/mysql/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql
    copying HMpTy/mysql/conesearch.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql
    copying HMpTy/mysql/add_htm_ids_to_mysql_database_table.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql
    creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/commonutils
    copying HMpTy/commonutils/getpackagepath.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/commonutils
    copying HMpTy/commonutils/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/commonutils
    creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm/tests
    copying HMpTy/htm/tests/test_htm.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm/tests
    copying HMpTy/htm/tests/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm/tests
    copying HMpTy/htm/tests/test_sets.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/htm/tests
    creating build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql/tests
    copying HMpTy/mysql/tests/test_conesearch.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql/tests
    copying HMpTy/mysql/tests/__init__.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql/tests
    copying HMpTy/mysql/tests/test_add_htm_ids_to_mysql_database_table.py -> build/lib.macosx-10.7-x86_64-2.7/HMpTy/mysql/tests
    copying HMpTy/default_settings.yaml -> build/lib.macosx-10.7-x86_64-2.7/HMpTy
    running build_ext
    building 'HMpTy.htm._htmc' extension
    creating build/temp.macosx-10.7-x86_64-2.7
    creating build/temp.macosx-10.7-x86_64-2.7/HMpTy
    creating build/temp.macosx-10.7-x86_64-2.7/HMpTy/htm
    creating build/temp.macosx-10.7-x86_64-2.7/HMpTy/htm/htm_src
    gcc -fno-strict-aliasing -I/Users/sherrysheng/opt/anaconda3/envs/sherlock/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/sherrysheng/opt/anaconda3/envs/sherlock/lib/python2.7/site-packages/numpy/core/include -IHMpTy/include -IHMpTy/htm -IHMpTy/htm/htm_src -I/Users/sherrysheng/opt/anaconda3/envs/sherlock/include/python2.7 -c HMpTy/htm/htm_src/VarStr.cpp -o build/temp.macosx-10.7-x86_64-2.7/HMpTy/htm/htm_src/VarStr.o -arch i386 -arch x86_64
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    In file included from HMpTy/htm/htm_src/VarStr.cpp:14:
    HMpTy/htm/htm_src/VarStr.h:33:10: fatal error: 'iostream' file not found
    #include <iostream>
             ^~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/sherrysheng/opt/anaconda3/envs/sherlock/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-install-JD5mtR/HMpTy/setup.py'"'"'; __file__='"'"'/private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-install-JD5mtR/HMpTy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/md/qwwkr3852rg4nx5pwh7ljyjr0000gn/T/pip-record-9RwwVX/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by genghisken** [comment]
Yes - seen this before!  Try

```export CFLAGS='-stdlib=libc++'```

Then try and pip install sherlock!
