### ISSUE TITLE
Bright nearby galaxy missed by sherlock

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/sherlock#95]
See this ATLAS source:

https://star.pst.qub.ac.uk/sne/atlas4/candidate/1145713851494028200/

flagged as orphan but there is a bright nearby galaxy

**Comment by thespacedoctor** [comment]
Took me a while to figure this one out. Turns out it's down to the morphology measurements of the galaxy. 

The galaxy is [NGC 5804](http://ned.ipac.caltech.edu/cgi-bin/objsearch?search_type=Obj_id&objid=39487&objname=38&img_stamp=YES&hconst=73.0&omegam=0.27&omegav=0.73&corr_z=1) and has a semi-major axis of 0.9 arcmin.

I include in the algorithm a *galaxy radius stretch factor* parameter currently set at 1.2 .

The distance from the transient to the core of NGC 5804 = 71.6''
But the match limit based on the galaxy morphology is 0.9 x 60 x 1.2 = 64.8" ... hence a match was rejected.

We can certainly increase the stretch factor in the setting files. I think increasing to 1.5 shouldn't introduce too many false-positive matches.

@genghisken can you do this for ATLAS, PanSTARRS and Lasair? I'll do so for my projects.

**Comment by thespacedoctor** [comment]
Now matched in Marshall with new settings:

![](https://live.staticflickr.com/65535/49622082656_baeef9abe0_o.png)

![](https://live.staticflickr.com/65535/49622081891_f50e2ea267_o.png)

**Comment by smarttgit** [comment]
But the galaxy has a redshift, and we have a physical separation limit of 50 kpc. So how does the 50kpc radius work when we  also have a  1.2 * semi_major_axis criteria (noticed this also in the ATLAS paper, and flagged it).

**Comment by smarttgit** [comment]
Also, I think you are actually using 
2.4 * semi_major_axis  == 1.2 * major_diameter 

Since major_diameter for this is set at 0.9 arcmin in NED 

That is better than 1.2 * semi_major_axis since I think that is too small. But still not sure which has precedence - the 1.2*major_diameter or the physical 50 kpc ?

**Comment by thespacedoctor** [comment]
> 2.4 * semi_major_axis == 1.2 * major_diameter

Ah yes, of course, you're right. I meant major diameter ... slip of the keyboard! 

Re. morphology and physical separation: they are joined with an AND. So the first check is with morphology measurements and then physical distance. My original reasoning behind this was that the morphology measurements (if present) are intrinsic to the galaxy but the 50kpc physical distance limit is a one size fits all. My original thinking was that 1.2 * major_diameter was very generous, but could stop mismatches of transients matched > 40 kpc away from smaller compact galaxies.

The biggest dangers here are the edge cases where a transient *is* associated with the galaxy but the morphology excludes it. The transient would typically then get flagged as an ORPHAN .. not so bad.

Obviously bad science to go on the statistics of one ... but the exemplar transient reported here, ATLAS20hgv, was typed as a SN Ia at z~0.07 and therefore not associated with NGC 5804.

I think the question here might be 'Do we want to optimise Sherlock to maximise correct associations and minimise mis-associations or optimise to minimise the risk of over-looking transients that may be within 100Mpc (with the expense of a few more mis-associations)?'

I'm not sure what the answer should be - but these are all parameters that can be adjusted in the algorithm settings files and not in the code ... therefore the answer can be different for different projects.

**Comment by smarttgit** [comment]
Just to tie up - 

Let's leave at 2.4 times semi-major axis radius = 1.2 times semi-major diameter. We may adjust this for ATLAS.
